### ISSUE TITLE
Update nodeenv to version 1.1.0

### ISSUE THREAD

**Issue by pwilkins** [CLIxIndia-Dev/qbank-lite#8]
The ``nodeenv`` Nodejs package is now at version 1.1.0.  The update is necessary for support of 32-bit Windows.  See the notes here:
[nodeenv release 1.1.0](https://github.com/ekalinin/nodeenv/releases/tag/1.1.0)

The ``requirements.txt`` needs to change.

@cjshawMIT

**Comment by cjshawMIT** [comment]
Okay, sounds good. Do you want to go ahead and make the change, and assign me to the PR?

**Comment by pwilkins** [comment]
Opened PR [9](https://github.com/CLIxIndia-Dev/qbank-lite/pull/9) to address this issue.

**Comment by cjshawMIT** [comment]
merged in PR 9
